source 'http://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'activerecord', '~> 4.2', '>= 4.2.6', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sinatra-contrib'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'scrypt'
gem 'haml'
gem 'tux'
gem 'omniauth'
gem 'pry-byebug'
gem 'pry-doc'
gem 'twitter'
gem 'devise'
gem 'annotate'
gem 'squeel'
gem 'sorcery'
gem 'activesupport'
gem 'authlogic'
gem 'rack'
gem 'nokogiri'
gem 'mechanize'
gem 'google_maps_service'
gem 'whenever'
gem 'capybara'

# HTML表示のテンプレートに使う
gem 'slim'
# 画像ファイル管理に使う
gem 'carrierwave'
gem 'mini_magick'
gem 'poltergeist'
gem 'acts_as_commentable_with_threading'
gem 'omniauth-google-oauth2'
gem 'omniauth-oauth2'
gem 'google-api-client', '~> 0.11'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
end
